# Generated by Django 6.0.6 on 2026-06-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
